package org.iesalandalus.programacion.tallermecanico.vista;

public enum Opcion {
 INSERTAR_CLIENTE(),
 INSERTAR_VEHICULO(),
 INSERTAR_REVISION(),
 BUSCAR_CLIENTE(),
 BUSCAR_VEHICULO(),
 BUSCAR_REVISION(),
 MODIFICAR_CLIENTE(),
 ANADIR_HORAS_REVISION(),
 ANADIR_PRECIO_MATERIAL_REVISION(),
 CERRAR_REVISION(),
 BORRAR_CLIENTE(),
 BORRAR_VEHICULO(),
 BORRAR_REVISION(),
 LISTAR_CLIENTE(),
 LISTAR_VEHICULOS(),
 LISTAR_REVISIONES(),
 LISTAR_REVISIONES_CLIENTES(),
 LISTAR_REVISIONES_VEHICULO(),
 SALIR();
